language: python

python:
    - "3.5"
    - "3.6"

install:
  # install deps
  - pip install -r requirements.txt
  - pip install pytest-cov mock assertpy python-coveralls
  - pip list

script:
  - py.test -v --cov netboot_config --cov-report term-missing

after_success:
  - coveralls
